/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2022 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */
#include<stdio.h>
#include <stdint.h>
#include<system_stm32f4xx.h>
#include<stm32f401re_gpio.h>
#include<led.h>
#include<stm32f401re_rcc.h>
#include<button.h>
void mainInit();
static void ButtonB2_Init(void){
	GPIO_InitTypeDef GPIO_InnitStructure;
	RCC_AHB1PeriphClockCmd(RCC_AHB1Periph_GPIOB, ENABLE);
	GPIO_InnitStructure.GPIO_Pin = GPIO_Pin_3;
	GPIO_InnitStructure.GPIO_Mode = GPIO_Mode_IN;
	GPIO_InnitStructure.GPIO_Speed = GPIO_Speed_50MHz;
	GPIO_InnitStructure.GPIO_PuPd = GPIO_PuPd_UP;
	GPIO_Init(GPIOB, &GPIO_InnitStructure);
}
int main(void){
	mainInit();
	while(1){
		if (GPIO_ReadInputDataBit(GPIOB, GPIO_Pin_3) == 0) {
			LedControl_SetColorIndividual(LED_KIT_ID0, LED_COLOR_GREEN, 100);
		}
		else{
			LedControl_SetColorIndividual(LED_KIT_ID0, LED_COLOR_GREEN, 0);
		}
	}
}

void mainInit(){
	SystemCoreClockUpdate();
	LedControl_Init();
	ButtonB2_Init();
}
